from io import BytesIO
from datetime import datetime
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH


def write_docx(content: str, week_date: str = None) -> BytesIO:
    doc = Document()
    week_date = week_date or datetime.now().strftime("%B %d, %Y")

    # Title
    title = doc.add_heading(f"CoSN Newsletter Draft — Week of {week_date}", level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph("")

    # Write content — split on double newlines as sections
    sections = content.strip().split("\n\n")
    for section in sections:
        lines = section.strip().splitlines()
        if not lines:
            continue
        first_line = lines[0]
        # Treat lines that look like headings (short, no period, all caps or title-ish)
        if len(first_line) < 80 and first_line == first_line.upper() and len(lines) == 1:
            doc.add_heading(first_line, level=2)
        elif len(first_line) < 80 and first_line.endswith(":"):
            doc.add_heading(first_line.rstrip(":"), level=2)
            for line in lines[1:]:
                doc.add_paragraph(line)
        else:
            doc.add_paragraph(section)

    # Footer
    doc.add_paragraph("")
    footer_para = doc.add_paragraph(
        f"Generated by CoSN Agent Dashboard on {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}"
    )
    footer_para.runs[0].font.size = Pt(9)
    footer_para.runs[0].font.italic = True
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    buf = BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf
