"""Generate a downloadable .docx from the Claude output."""
import io
import re
from datetime import datetime, timezone

from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def _add_styled_paragraph(doc: Document, text: str) -> None:
    para = doc.add_paragraph(text)
    para.style.font.size = Pt(11)


def generate_docx(content: str, model: str = "claude-sonnet-4-6") -> bytes:
    """
    Convert the Claude-generated newsletter text into a formatted .docx.
    Returns raw bytes suitable for st.download_button.
    """
    doc = Document()

    # ── Document title ──────────────────────────────────────────────────────
    today = datetime.now(timezone.utc).strftime("%B %d, %Y")
    title_para = doc.add_heading(f"CoSN Newsletter Draft — Week of {today}", level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.LEFT
    for run in title_para.runs:
        run.font.color.rgb = RGBColor(0x0A, 0x25, 0x40)

    doc.add_paragraph()  # spacer

    # ── Body content (parse markdown-style headings) ──────────────────────
    for line in content.splitlines():
        stripped = line.rstrip()

        if stripped.startswith("### "):
            doc.add_heading(stripped[4:], level=3)
        elif stripped.startswith("## "):
            doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith("# "):
            doc.add_heading(stripped[2:], level=1)
        elif stripped.startswith("**") and stripped.endswith("**"):
            # Bold-only line — treat as a minor heading
            para = doc.add_paragraph()
            run = para.add_run(stripped.strip("*"))
            run.bold = True
            run.font.size = Pt(11)
        elif stripped == "---" or stripped == "***" or stripped == "___":
            # Horizontal rule — add a blank line
            doc.add_paragraph()
        elif stripped == "":
            doc.add_paragraph()
        else:
            # Inline bold (**text**) support
            para = doc.add_paragraph()
            parts = re.split(r"(\*\*[^*]+\*\*)", stripped)
            for part in parts:
                if part.startswith("**") and part.endswith("**"):
                    run = para.add_run(part[2:-2])
                    run.bold = True
                else:
                    para.add_run(part)
            for run in para.runs:
                run.font.size = Pt(11)

    # ── Footer ───────────────────────────────────────────────────────────────
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    section = doc.sections[0]
    footer_para = section.footer.paragraphs[0]
    footer_para.text = (
        f"Generated by CoSN Agent Dashboard on {generated_at} via Claude {model}"
    )
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in footer_para.runs:
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0x6B, 0x7C, 0x93)

    # ── Serialize ────────────────────────────────────────────────────────────
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()
